import { StyleSheet, TextInput, View } from "react-native";
import Logo from "../../../../Components/Logo";
import { Bar, TextTitlePassWord, Conteiner, TextInfoForgots, TouchableOpacityBackGraudWhite, TextBlack, TouchableOpacityWithoutStyling, TextWhite } from "../../../../Components/Styles/styles";

const Screen2 = ({ navigation }) => {
    return (
        <Conteiner>
            <Logo />
            <TextTitlePassWord>Write the code</TextTitlePassWord>
            <Bar/>

            <TextInfoForgots>Enter the code that was sent to your email, the (n) digit code was generated by the authentication application.</TextInfoForgots>

            <View style={styles.conteiner}>
            <TextInput style={styles.input}/>
            <TextInput style={styles.input}/>
            <TextInput style={styles.input}/>
            <TextInput style={styles.input}/>
            <TextInput style={styles.input}/>
            </View>

            <TouchableOpacityBackGraudWhite onPress={() => navigation.push('Screen3')}> 
                <TextBlack>Avançar</TextBlack>
            </TouchableOpacityBackGraudWhite>

            <TouchableOpacityWithoutStyling onPress={() => navigation.push('Screen1')}>
                <TextWhite>Back</TextWhite>
            </TouchableOpacityWithoutStyling>
        </Conteiner>
    )
}

const styles = StyleSheet.create({
    conteiner: {
        flexDirection: 'row',
        justifyContent:'center',
    },
    input:{
        backgroundColor:"#fff",
        borderRadius: 5,
        height: 50,
        width: 60,
        textAlign:'center',
        marginBottom: 50,
        marginLeft: 5
    }
})

export default Screen2;